version: '3.7'

services:
  app:
    container_name: robot
    build: .
    image: robot:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - LOGLEVEL=DEBUG
    restart: always
